// lib/supabase/database.types.ts
// This file will be auto-generated by Supabase CLI.
// run `pnpm supabase:generate-types`

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

// You can add any global types or interfaces relevant to your Supabase schema here
// if they are not directly generated, though it's best to rely on generation. 